### ISSUE TITLE
Keyboard focus is outside window with XULRunner 1.9.2 and + 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#13] opened 2010-10-27 18:55 UTC
How to reproduce: 

Edit the run script, or call the app with cfx using -a xulrunner -b path_to_xulrunner-bin. Use the "thumbnails/index.html". Put the cursor caret in the textfield ( urlbar ) at the top. Type in something and you will notice the focus is still in the terminal console instead the window. 

how to launch with XULrunner: 

./impl/bin/cfx -a xulrunner -b ../../xulrunner-sdk/xulrunner-sdk/bin/xulrunner-bin -t ./template/app-extension --static-args {\"browser\":\"thumbnails/index.html\"} -p \"impl/package/chromeless\" run

**Comment by clarkbw** [comment] 2010-10-27 19:22
I have a quick fix for those with this problem, i wrote a [gist](http://gist.github.com/645540) that uses your installed Firefox xulrunner (which works assuming you have 3.6 installed)

**Comment by lloyd** [comment] 2010-10-27 23:58
I know that osx launches applications differently (app.app) than raw binaries,  a wild theory is that we can solve this problem by a prelaunch step that builds up an XXX.app directory with symlinks and such and moves xul in...

**Comment by taboca** [comment] 2010-10-28 00:45
I think xulrunner has an option to do this generation. But Looks like, I feel, this is simply a bug. Notice I can click in the markup and select, with the mouse, just the keyboard focus was moved away. I wonder.

**Comment by taboca** [comment] 2010-10-28 01:24
I also confirm that this problem does not happen with Linux using XULRunner 1.9.2

**Comment by lloyd** [comment] 2010-11-09 00:15
https://developer.mozilla.org/en/XULRunner/Creating_custom_app_bundles_for_Mac_OS_X

**Comment by taboca** [comment] 2010-11-09 19:06
The  app bundle packaging, indeed, fixes. which we will enable via a fix with a build script ( another issue ) . But this bug I feel is simply a cfx <-> xulrunner issue.

**Comment by taboca** [comment] 2010-11-11 19:07
I have landed a xulrunner packaging option, so the final install mode does not have this bug. I am keeping this open til Lloyd does a review, notice that in cfx run mode, we still trap the focus https://github.com/mozilla/chromeless/commit/2129cee409b4aba49e94ada734456c84d3388efc

**Comment by taboca** [comment] 2010-11-30 17:05
I rested this yesterday with another XULRunner application, ChatZilla -- it also shows the problem if you launch ChatZilla from the command line. So this has to do with launching in Mac OSX from the command line. 

For us, we can use a build browser in Mac OSX using the xulrunner --install-app option and launching the app from the Applications/Mozilla/Chromeless.app -- then the problem is not shown. Marking fixed.

**Comment by lloyd** [comment] 2010-12-09 18:55
Still don't think this is a solution.  It requires the user to install xulrunner, and worse, understand it.  I think your average web dev will just up an walk away at this point.

I think the requirement for a solution is that:

./chromeless 

launches an application with proper focus.

**Comment by benfrancis** [comment] 2011-01-07 20:40
Can confirm that this bug prevented me developing using Chromeless under OS X on my laptop, restricted to Linux on my desktop.

Would appreciate a fix or detailed workaround as don't quite understand the fixes described in the comments on this bug.

Thanks!

**Comment by lloyd** [comment] 2011-01-12 18:31
hey hippygeek!

This bug is fixed on the appify branch which I hope to merge shortly.  If you like you can try to switch to that branch and run your application.  What happens there is it builds up a standalone application (symlinked into your browsercode) and launches the app.

There are some other developer usability issues I'm working on now (like console logging and proper process killing), and will merge to master once it's got review and those are figured out.

**Comment by lloyd** [comment] 2011-01-12 18:31
hey hippygeek!

This bug is fixed on the appify branch which I hope to merge shortly.  If you like you can try to switch to that branch and run your application.  What happens there is it builds up a standalone application (symlinked into your browsercode) and launches the app.

There are some other developer usability issues I'm working on now (like console logging and proper process killing), and will merge to master once it's got review and those are figured out.

**Comment by lloyd** [comment] 2011-01-13 10:30
merged to master, this issue is fixed.  finally.

**Comment by benfrancis** [comment] 2011-01-13 17:13
I just pulled the latest version from git and I'm getting an error when I try and run ./chromeless with the example browsers on OS X

 chromeless/impl/appifier/_osx.py:15: Warning: 'with' will become a reserved keyword in  Python 2.6
 Traceback (most recent call last):
  File "./chromeless", line 89, in <module>
    "-p", "packages/chromeless"
  File "/Users/tola/code/mozilla/chromeless/impl/cuddlefish/__init__.py", line 567, in run
    a = appifier.Appifier()
  File "/Users/tola/code/mozilla/chromeless/impl/appifier/_appifier.py", line 15, in    __init__
    import _osx as osappifier
  File "/Users/tola/code/mozilla/chromeless/impl/appifier/_osx.py", line 15
    with open(src, 'r') as f:
            ^
 SyntaxError: invalid syntax

**Closed as completed** 2011-01-13 18:30 UTC

**Comment by benfrancis** [comment] 2011-01-13 21:20
(Although this is only a warning, I can't seem to get Chromeless to run. Note that I currently only have Python 2.5.1 installed on my Mac which is the one which comes with OS X 10.5 which I'm guessing could be the reason. Anyone else reproduced this problem?)

**Comment by lloyd** [comment] 2011-01-13 22:38
hey hippygeek,

try adding this to the top of _osx.py:

from **future** import with_statement 

I don't have a 10.5 box to test on, but expect this will solve the problem?

**Comment by benfrancis** [comment] 2011-01-13 23:09
Thanks for that Lloyd,

It did get rid of the warning but that just revealed some other underlying problems like not recognising os.path.relpath in _os.py

I've now installed Python 2.7 and put #!/usr/local/bin/python2.7 at the top of the chromeless script and it all works fine!

To be fair the README does state that it isn't fully tested in Python 2.5

I'm not sure how much of a priority it really is to support older versions of Python

Thanks for the keyboard focus fix anyway :)

**Comment by lloyd** [comment] 2011-01-14 08:34
yeah, typically before we tag marcio and I will test on 10.6, 10.5, linux 32bit, linux 64bit, and windoze.  

Being somewhat of a python n00b I've just recently realized that there's significant differences between 2.6 and 2.5.  I'm slurping down python25 from macports now, at least that'll let me test 2.5 from time to time.

I think 2.5 support is important because it's the default on many linux systems, and on osx 10.5, so if it doesn't just work then a developers first moments with chromeless will be unpleasant.

**Comment by lloyd** [comment] 2011-01-14 09:03
ok, as of this commit, chromeless under python 2.5 on osx is fixed:

https://github.com/mozilla/chromeless/commit/1a8cd566d94fd7b467055ba8514250480d3bbb42

**Comment by benfrancis** [comment] 2011-01-14 10:01
Cool, I can confirm this works in OSX (10.5) and Python 2.5.1.
