### ISSUE TITLE
Option for menu bar should be changable

### ISSUE THREAD

**Issue by slbug** [mozilla/chromeless#58] opened 2011-02-13 07:48 UTC
Right now toolbox hardcoded into blankXul variable, also menubar=yes hardcoded. 

I don't want to use menubar at all (it just shows as empty space) and i can't remove it.

**Comment by lloyd** [comment] 2011-02-13 07:54
Thinking an entry in appinfo.json would be the way to go with this, default maybe is on, parameter ignored on osx.  "menubar": false

Thanks for the report!  Should be able to look in the next few days.

**Comment by lloyd** [comment] 2011-02-15 02:51
implement menubar and resizable properties in appinfo.json. Closed by 0028a274cdb653fe3803a4ff20e3ed1c200069cf.  Closed by 0028a274cdb653fe3803a4ff20e3ed1c200069cf

**Comment by lloyd** [comment] 2011-02-15 02:55
oops, last commit almost got it.  need to figure out what needs to change in `chromeless-sandbox-window.js`.  The config params are passed through, will fix first thing in the morn'.

**Comment by lloyd** [comment] 2011-02-15 03:02
Last update for the day, it seems menubar=no does not properly hide the menu (at least on linux).  we may want to enable programmatic hidding via menu.js, and then have the appinfo.json config item invoke that...

**Comment by mikedeboer** [comment] 2011-02-15 10:21
This issue has been fixed in Prism before, and it's rather trivial to do this in chromeless as well. If you want I can propose a fix in a pull request later on...

**Comment by lloyd** [comment] 2011-02-15 16:40
yo mike.  crawling around prism source code it looks like they simply hide the dom node.  I'm thinking we might want to just emulate that approach.  if `menu.js` were to expose show() and hide() methods which just toggle visibility of the &lt;menubar&gt;, then it seems like we'd be golden.  Pretty simple approach.  visibility wouldn't affect keybindings set via menu.

The question of defaults arises.  Here's a rough proposal:
- On OSX the default would be a basic application menu with quit pre-bound (perhaps also an About... box)
- On windows and linux I'm on the fence. I'm thinking default menubar visible, and same features as the osx menu.

**Comment by taboca** [comment] 2011-03-16 21:38
Comment from Ben Francis, that is working on a Chromeless-based project: 

"I was actually able to fix this locally with it defaulting to having
no menu by simply conditionally concatenating the toolbox & menu bar
to the blankXul string based on the options.menubar boolean variable,
but the proposal is to have a default set of menus and I wasn't sure
how to implement that."

I see that the current proposal is to hide visibility via the developer's JS. The problem with that is that menus are doing to appear and quickly disappear -- I am not sure this is the expected behavior. We may also want to consider not inserting the XUL menu code too? and then let the require break. Other appraoch would be to have default = no menu, then if user wants, they do something like overlay=menu using the app.json.

**Comment by taboca** [comment] 2011-03-17 00:58
Checked this option to remove via the require("menu") but this is not friendly with the very original case filed in the bug. I think we need to have the appinfo.json to bypass the whole menu. 

Ben, please check this if you get a chance: 

https://github.com/mozilla/chromeless/tree/dev_menu_hide

**Comment by benfrancis** [comment] 2011-03-17 13:35
It's probably a good idea to have hide() and show() methods if the menu is turned on but it seems more efficient never to create the toolbox and menubar elements at all if menu is turned off in the app manifest.

As for what the defaults should be, that's a little tricky. If it was just for Windows and Linux I'd argue it should be off by default, but menus aren't really optional in OS X because of the way the interface is structured so the only way to be consistent across all platforms is to have the same default menus for all.

I'm not actually using menus at all in my current app so I don't have any specific needs in that respect.

**Comment by taboca** [comment] 2011-03-17 21:51
Olay, thanks for the input. The proposed patch does the follow: 

1) appinfo.json with no menubar property = defaults to menu XUL code, then the menu.hide() can be used.
2) appinfo.json with menubar:false, does not even include the menu ( comment 885032 )

Here is where we do the check: 

https://github.com/mozilla/chromeless/commit/0ec199c1af59561a0bd2150b37682a4c4eab3ede

Please provide feedback if this is okay.

**Comment by benfrancis** [comment] 2011-03-18 17:19
Should that not be:
    var menubar = "";

```
if (typeof(ai.menubar) === "undefined" || ai.menubar == true) {
    var menubar ='<toolbox id="theTopToolbox" style="padding: 0; border: 0; margin: 0;">' +
             '<menubar id="theMenuBar" style="padding: 0; border: 0; margin: 0;">' +
             '</menubar>' +
             '</toolbox>';
} 
```

Currently there's no menu if you set menubar to true in the manifest

**Comment by taboca** [comment] 2011-03-18 19:06
Thank you for the review SHA: 9d2f358ba88dd8ad35b2c773726ac5a3ebaf2c87

**Comment by taboca** [comment] 2011-03-27 23:16
sha: febca4f299e6feb0caf1d2fecfd17cc20e5b9a37

**Closed as completed by taboca** 2011-03-27 23:16 UTC
Labels:    ✔✔✔

**Comment by taboca** [comment] 2011-03-28 00:12
I was going to check the hide() DOM approach, but I feel it does not make sense because the actual implementation that works is via removing nodes, not via style changes. And if we go in the direction to remove nodes ( erase, not hide ) then right, it's just a developer's decision to remove one node or another. Let's just let them see the XUL object tree or equivalent is what I recommend. Then we could get rid of all the JS-based "DOM-like" structure way of populating this menu?

**Comment by benfrancis** [comment] 2011-03-29 09:42
That sounds sensible. "Hide" should definitely "hide" the element via style changes, not "remove" the node from the DOM.

**Comment by benfrancis** [comment] 2011-03-29 09:42
That sounds sensible. "Hide" should definitely "hide" the element via style changes, not "remove" the node from the DOM.
